version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database
    command: --require_secure_transport=ON
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 1s
      retries: 5
  server:
    build:
      context: .
    restart: always
    environment:
      GIN_MODE: debug
      HOST: 0.0.0.0
      PORT: 8888
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: example
      DB_NAME: database
      TLS_OPTION: skip-verify
    ports:
      - 8888:8888
    depends_on:
      db:
        condition: service_healthy
